# This is a basic workflow to help you get started with Actions

name: java17

# Controls when the workflow will run
on:
 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Set up JDK 11 for toolchains
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 11
    - name: Set up JDK 8 for toolchains
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 8
    - name: Set up JDK 
      uses: actions/setup-java@v1.3.0
      with:
        java-version: ${{ matrix.java }}
    - name: Inspect environment
      run: |
        set | grep JAVA
